### ISSUE TITLE
Can you provide 2022 Mca paper?

### ISSUE THREAD

**Issue by sankethp44** [outofcoolage/PGCET-MCA-Study-Material-and-Previous-year-Question-Papers#1]
Please provide **Mca 2022** paper, thank you @outofcoolage

**Comment by outofcoolage** [comment]
I have the papers but it has a lot of workings around them as I had myself appeared for the exam :)

**Comment by sankethp44** [comment]
Not a problem, If the questions are visible that's enough! Can you send it?

**Comment by outofcoolage** [comment]
Uploaded the PGCET MCA 2022 Question paper along with the official answer key in the answer key folder.
All the best for you preparation

**Comment by outofcoolage** [comment]
@sankethp44  
PGCET MCA 2022 Paper Link : https://github.com/outofcoolage/PGCET-MCA-Study-Material-and-Previous-year-Question-Papers/blob/main/Previous%20Year%20QP/MCA_2022.pdf
Answer Key Link: https://github.com/outofcoolage/PGCET-MCA-Study-Material-and-Previous-year-Question-Papers/blob/main/Previous%20Year%20QP/Answer%20Key/MCA_2022_B1_KEY.pdf
