### ISSUE TITLE
MCA Model Question Paper

### ISSUE THREAD

**Issue by Rajlohith** [outofcoolage/PGCET-MCA-Study-Material-and-Previous-year-Question-Papers#2]
I have an official model question paper of MCA by KEA, I think it can be useful with the other question paper together
[MCA Mock Paper.pdf](https://github.com/outofcoolage/PGCET-MCA-Study-Material-and-Previous-year-Question-Papers/files/12217182/MCA.Mock.Paper.pdf)

**Comment by outofcoolage** [comment]
@MrBadAttitude added to the main branch. Thank you:)
